name: Build Workflow

on: push

env: 
  ARTIFACT_ID: household-management

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    
    - name: Build
      id: build
      run: | 
        chmod +x mvnw
        ./mvnw clean package
        echo "::set-output name=artifact-id::$( ls target/*jar | awk -F'/' '{print $2}' )"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build.outputs.artifact-id }}
        path: target/${{ steps.build.outputs.artifact-id }}
    
    - name: Upload artifact to release page
      uses: softprops/action-gh-release@v1
      if: startsWith( github.ref, 'refs/tags/' )
      with:
        files: target/${{ steps.build.outputs.artifact-id }}

    - name: Check hash value for jar
      run: sha1sum target/${{ steps.build.outputs.artifact-id }}
    
    - name: Show artifact download commands
      run: |
        echo '$ read TOKEN'
        echo '$ curl -s -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${TOKEN}" \
          ${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
          | jq -r '.artifacts[0].archive_download_url' \
          | (read URL ; curl -L -H "Authorization: token ${TOKEN}" -o ${{ steps.build.outputs.artifact-id }}.zip ${URL})'
        echo '$ unzip ${{ steps.build.outputs.artifact-id }}.zip'
