name: build

on: push

env: 
  ARTIFACT_ID: household-management

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: maven
      run: chmod +x mvnw && ./mvnw clean package
    - name: copy jar
      run: mkdir artifact && cp target/*.jar artifact
    - name: upload jar
      uses: actions/upload-artifact@v3
      with:
        name: deliverables
        path: artifact
    - name: Check hash value for jar
      run: sha1sum target/*.jar
    - name: Show artifact download commands
      run: |
        echo '$ read TOKEN'
        echo '$ curl -s -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${TOKEN}" \
          ${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
          | jq -r '.artifacts[0].archive_download_url' \
          | (read URL ; curl -L -H "Authorization: token ${TOKEN}" -o ${{ env.ARTIFACT_ID }}.zip ${URL})'
        echo '$ unzip ${{ env.ARTIFACT_ID }}.zip'
